source "https://rubygems.org"

# GitHub Pages gem includes Jekyll and common plugins
gem "github-pages", group: :jekyll_plugins

# Additional gems
gem "webrick", "~> 1.8"

# Optional: AsciiDoc support
# gem "jekyll-asciidoc"

# Jekyll plugins
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end

# Windows and JRuby does not include zoneinfo files
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1", :install_if => Gem.win_platform?
